
###
GET http://localhost:3002/

###
POST http://localhost:3002/
Content-Type: application/json

{
    "name": "felix tito nina",
    "email": "email@outlook.com",
    "document": "43047717878"
    # "businessName": "businessName"
}